#!/bin/bash
# The MIT License (MIT)
#
# Copyright (c) 2016 9Space Pty Ltd
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

### BEGIN INIT INFO
# Provides:          $location
# Short-Description: This shell script takes care of starting and stopping
#		     nine-cloud-control (the $location Control)
# Description:       $location Control environment for building and deployment containers on AWS using Kubernetes.
#
#
### END INIT INFO

if [ "$NINE_CLOUD_DEBUG" != "" ]; then
    echo ncloud:debug NCSHELL
fi

if [ "$NINE_CLOUD_ROOT" == "" ]; then
    is_link=$(readlink $0)
    if [ "$is_link" != "" ]; then
        export NINE_CLOUD_ROOT=`dirname $(readlink $0)`
    else
        export NINE_CLOUD_ROOT=`dirname $0`
        if [ "$NINE_CLOUD_ROOT" == "." ]; then
            export NINE_CLOUD_ROOT=$(pwd)
        fi
    fi
fi

source $NINE_CLOUD_ROOT/lib/init

location=`hostname | sed -e "s/\.local//g"`

PROMPT_COMMAND="prompt_update"
